import { LIVING } from "./tags";
import {
  Archer,
  Bandit,
  Champion,
  Monk,
  Piper,
  RageKnight,
  Rat,
  RoyalGuard,
  ShellKnight,
  TheKing,
  Villager,
  Wizard,
} from "./objects";
import { randomInt } from "./helpers";
import { GameObject } from "./game";

// Signals (positive signals are spawn counters)
const END_OF_LEVEL = 99;
const END_OF_WAVE = 98;

// Spawn IDs
const VILLAGER = 0;
const ARCHER = 1;
const MONK = 2;
const CHAMPION = 3;
const PIPER = 4;
const RAGE_KNIGHT = 5;
const ROYAL_GUARD = 6;
const SHELL_KNIGHT = 7;
const WIZARD = 8;
const THE_KING = 9;
const RAT = 10;
const MOB = 11;
const BANDIT = 12;

type Spawn = () => GameObject;

const LOOKUP: Spawn[] = [
  Villager,
  Archer,
  Monk,
  Champion,
  Piper,
  RageKnight,
  RoyalGuard,
  ShellKnight,
  Wizard,
  TheKing,
  Rat,
  Villager,
  Bandit,
];

const DELAYS: Record<string | number, () => number> = {
  [RAT]: () => randomInt(500),
  [VILLAGER]: () => randomInt(200),
  [BANDIT]: () => randomInt(200),
  [MOB]: () => -randomInt(500),
};


const LEVELS = [
  // Level 1
  1, VILLAGER, END_OF_WAVE,
  2, VILLAGER, END_OF_WAVE,
  3, VILLAGER, END_OF_WAVE,
  4, VILLAGER, 1, BANDIT, END_OF_LEVEL,

  // Level 2 (introducing ARCHER)
  1, VILLAGER, 1, BANDIT, 
  1, VILLAGER, 1, BANDIT, 3, VILLAGER, END_OF_WAVE, /**5V,2B*/
  
  1, VILLAGER, 1, BANDIT, 
  1, VILLAGER, 1, BANDIT, 
  1, VILLAGER, 1, BANDIT, 3, VILLAGER, END_OF_WAVE,/**6V,3B */
  
  1, VILLAGER, 1, BANDIT, 
  1, VILLAGER, 1, BANDIT, 
  1, VILLAGER, 1, BANDIT, 
  2, VILLAGER, 1, BANDIT, 
  2, VILLAGER, END_OF_WAVE, /**7V,4B */
  
  1, BANDIT, 2, VILLAGER, 
  1, BANDIT, 2, VILLAGER, 
  1, BANDIT, 2, VILLAGER, 
  2, BANDIT, 2, VILLAGER, 1, ARCHER, END_OF_LEVEL, /**8V,5B,1A */

  // Level 3 (introducing MONK)
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 3, VILLAGER, 1, ARCHER, END_OF_WAVE, /**8V,6B,2A */
  
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER,  
  1, ARCHER, 1, BANDIT,  
  1, ARCHER, 2, VILLAGER, 1, ARCHER, END_OF_WAVE, /**8V,7B,3A */
  
  1, BANDIT, 1, VILLAGER, 1, ARCHER, 
  1, BANDIT, 1, VILLAGER, 1, ARCHER, 
  1, BANDIT, 1, VILLAGER, 1, ARCHER, 
  1, BANDIT, 1, VILLAGER, 1, ARCHER, END_OF_WAVE, /**8V,8B,4A */
  
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, VILLAGER, 1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 1, BANDIT, 1, MONK, END_OF_LEVEL, /**8V,8B,5A,1M */

  // Level 4 (introducing CHAMPION)
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,4A,1M */
 
  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, VILLAGER, 
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,4A,1M */

  1, BANDIT, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,5A,1M */

  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_LEVEL, /**6V,6B,6A,1M,1C */

  // Level 5 (introducing SHELL KNIGHT)
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,1M.1C */

  1, BANDIT, 1, ARCHER, 1, VILLAGER, 
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,2M.2C */

  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,3M,2C */

  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, BANDIT, 1, ARCHER, 1, VILLAGER, END_OF_LEVEL, /**6V,6B,6A,3M.2C,1S */

  // Level 6 (introducing PIPER)
  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1 ,BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,4M.4C,1S */

  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,5M.5C,2S */

  1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,5M.6C,3S */

  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER,
  1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, END_OF_WAVE, /**6V,6B,6A,5M.6C,4S */

  1, PIPER, END_OF_LEVEL,

  // Level 7 (introducing WIZARD)
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, END_OF_WAVE, /**7V,7B,7A,7M.7C,5S,2P */

  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, END_OF_WAVE, /**7V,7B,7A,7M.7C,5S,3P */

  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, END_OF_WAVE, /**7V,7B,7A,7M.7C,5S,4P */
  
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, END_OF_WAVE, /**7V,7B,7A,7M.7C,5S,5P */

  1, WIZARD, END_OF_LEVEL,

  // Level 8 (introducing RAGE KNIGHT)
  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**6V,6B,6A,6M.6C,5S,3P,1W */

  1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**6V,6B,6A,6M.6C,5S,4P,2W */

  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**6V,6B,6A,6M.6C,6S,4P,2W */

  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**6V,6B,6A,6M.6C,6S,5P,2W */

  1, RAGE_KNIGHT, END_OF_LEVEL,

  // Level 9 (introducing ROYAL GUARD)
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**5V,5B,5A,5M.5C,5S,5P,4W,1R */

  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**5V,5B,5A,5M.5C,5S,5P,4W,2R */

  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, /**5V,5B,5A,5M,5C,5S,5P,5W,3R */

  1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, SHELL_KNIGHT, 1, CHAMPION, 1 ,BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, RAGE_KNIGHT, 1, SHELL_KNIGHT, 1, CHAMPION, 1, BANDIT, 1, ARCHER, 1, VILLAGER, 1, MONK, 1, PIPER, 1, WIZARD, END_OF_WAVE, 
  1, ROYAL_GUARD, END_OF_LEVEL, /**5V,5B,5A,5M.5C,5S,5P,5W,4R */

  // Level 10 (introducing THE_KING)
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD,
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD, 
  1, ROYAL_GUARD, 1, SHELL_KNIGHT, 1, CHAMPION, 1, RAGE_KNIGHT, 1, ARCHER, 1, MONK, 1, PIPER, 1, WIZARD, 1, THE_KING, END_OF_LEVEL, /**6B,6A,6M.6C,6S,6P,6W,6R,1K */
];


let timer = 0;
let cursor = 0;

export function isLevelFinished() {
  return LEVELS[cursor] === END_OF_LEVEL && isCleared();
}

export function isComplete() {
  return cursor >= LEVELS.length - 1;
}

export let nextLevel = () => {
  cursor++;
  game.level++;
  game.onLevelStart();
};

export function updateLevel(dt: number) {
  let cmd = LEVELS[cursor];
  if ((timer -= dt) > 0) {}
  else if (cmd === END_OF_WAVE) isCleared() && cursor++;
  else if (cmd === END_OF_LEVEL) {}
  else if (cmd) {
    LEVELS[cursor]--; // Decrement quantity
    let id = LEVELS[cursor + 1];
    let unit = LOOKUP[id]();
    game.spawn(unit);
    timer = unit.updateSpeed + (DELAYS[id]?.() || 0);
  } else {
    cursor += 2;
  }
}

function isCleared() {
  return !game.objects.some(object => object.is(LIVING));
}
